### ISSUE TITLE
comment about *LOGFILELEVEL in README does not seem right

### ISSUE THREAD

**Issue by tfarina** [kala13x/slog#14]
Currently in the README file it says: "*LOGFILELEVEL is passed as fourth argument in slog_init()."

But that does not seem quite right, because the fourth argument is whether it should be thread safe or not.

**Comment by kala13x** [comment]
Yes, you are correct. With the last changes I made in this project, I removed LOGFILELEVEL parameter from initialization function and LOGTOFILE and LOGFILELEVEL parameters are disabled by default. 

If you want to enable and configure it, there is two way:
1) You can enable it from the config file and set log to file level
```
LOGTOFILE 1
LOGFILELEVEL 1
```
2) You can use simple API and on-the-fly change config parameters
```
SlogConfig cfg;
slog_config_get(&cfg);
cfg.nToFile = 1;
cfg.nFileLevel = 1;
slog_config_set(&cfg);
```
Both of them does the same.

P.S. Thanks for the comment, I will change README file.
