### ISSUE TITLE
Feature, adding pthread_self() and __FUNCTION it it?

### ISSUE THREAD

**Issue by Jeffreyvirobbins** [kala13x/slog#17]
https://github.com/kala13x/slog/blob/2f9b9ca1f0923c00a74259980377bc6970d58b49/src/slog.h#L64

**Comment by kala13x** [comment]
@Jeffreyvirobbins sorry for late answer. I have some unfinished parts of the new optimal version of this library where  "pthread_self()" is already implemented. I'm busy right now with a few tasks but I will finish and push the code in a few days.

**Comment by kala13x** [comment]
See new commit.
