### ISSUE TITLE
Could you please add support for rotating file log?

### ISSUE THREAD

**Issue by sddongxh** [kala13x/slog#20]
Thanks.

**Comment by kala13x** [comment]
@sddongxh Currently, slog is a lightweight, zero-dependency C library. Implementing log rotation functionality requires using one of the compression libraries like zlib or zstd, which would complicate the idea of building and running slog on all devices without dependencies. Currently, slog supports log_callback functionality, where logs can be collected and written to a file. This makes users able to write their own file-logging implementation and log rotation functionality accordingly.
