### ISSUE TITLE
Compiling slog with MSYS64 on Win11 64bits

### ISSUE THREAD

**Issue by tallaki74** [kala13x/slog#23]
Hello!
I like this slog lib.
I had to modify the `slog.c` to able to compile it with MSYS64 (on Win11 64bits).
- Replcaced macros `__FUNCTION__` by `__func__` to meet the C99 standard.
- There is no syscall.h in MSYS64, so I modified the next lines
  from these:
    ```
    #if !defined(__APPLE__) && !defined(DARWIN) && !defined(WIN32)
    #include <syscall.h>
    #endif
    ```
  to these:
    ```
    #if !defined(__APPLE__) && !defined(DARWIN) && !defined(WIN32) && !defined(__MSYS__)
    #include <syscall.h>
    #endif
    ```
- There is no syscall() and __NR_gettid in MSYS64, and no 32 bits but 64 bits, so I modified from `uint32_t` to `size_t` the next lines
  from these:
    ```
    static uint32_t slog_get_tid()
    {
    #if defined(__APPLE__) || defined(DARWIN) || defined(WIN32)
        return (uint32_t)pthread_self();
    #else
        return syscall(__NR_gettid);
    #endif
    }
    ```
  to these:
    ```
    static size_t slog_get_tid()
    {
    #if defined(__APPLE__) || defined(DARWIN) || defined(WIN32) || defined(__MSYS__)
        return (size_t)pthread_self();
    #else
        return syscall(__NR_gettid);
    #endif
    }
    ```
- I modified `%u` to `%lu` in the next lines
  from these:
    ```
    static void slog_create_tid(char *pOut, int nSize, uint8_t nTraceTid)
    {
        if (!nTraceTid) pOut[0] = SLOG_NUL;
        else snprintf(pOut, nSize, "(%u) ", slog_get_tid());
    }
    ```
  to these:
    ```
    static void slog_create_tid(char *pOut, int nSize, uint8_t nTraceTid)
    {
        if (!nTraceTid) pOut[0] = SLOG_NUL;
        else snprintf(pOut, nSize, "(%lu) ", slog_get_tid());
    }
    ```
Now, with these modifications I am able to compile the slog library without any warnings and errors with MSYS64 (on Win11 64bits).

**Comment by kala13x** [comment]
@tallaki74 Hello,

thank you very much for this information. The last time I had Windows was a year ago and I was not surprised by the changes. If you want, make a pull request, and I'll merge it. Otherwise, I will look at it more detail and manually move changes to the code this evening.

**Comment by tallaki74** [comment]
Please make changes because I don't know how to use github.

One more thing I noticed:
In the log file, the milliseconds not correct, the tenth of a second is always 0.
I modified the code and now the milliseconds are now correct in the log file.
In the `slog.h` file (`uint8_t` to `uint16_t`):
```
typedef struct SLogDate {
    uint16_t nYear;
    uint8_t nMonth;
    uint8_t nDay;
    uint8_t nHour;
    uint8_t nMin;
    uint8_t nSec;
    uint8_t nUsec;
} slog_date_t;

uint8_t slog_get_usec();
```
rewrite to these lines:
```
typedef struct SLogDate {
    uint16_t nYear;
    uint8_t nMonth;
    uint8_t nDay;
    uint8_t nHour;
    uint8_t nMin;
    uint8_t nSec;
    uint16_t nUsec;
} slog_date_t;

uint16_t slog_get_usec();
```
In the `slog.c` file (`uint8_t` to `uint16_t`, and `tv_usec / 10000` to `tv_usec / 1000`):
```
uint8_t slog_get_usec()
{
    struct timeval tv;
    if (gettimeofday(&tv, NULL) < 0) return 0;
    return (uint8_t)(tv.tv_usec / 10000);
}
```
rewrite to these lines:
```
uint16_t slog_get_usec()
{
    struct timeval tv;
    if (gettimeofday(&tv, NULL) < 0) return 0;
    return (uint16_t)(tv.tv_usec / 1000);
}
```
Thank you.

**Comment by kala13x** [comment]
@tallaki74  Thank you!

I Just pushed the changes to the master branch: https://github.com/kala13x/slog/commit/9c6e2133915aad4ee5ca227c97f3b33edef7c6f2

There are slightly different changes, but it should work on MSYS64 as well.

Instead of checking every platform with `ifdef`, I think its better to check `__linux__` only once:

```C
#ifdef __linux__
    return syscall(__NR_gettid);
#else
    return (slog_u32_t)pthread_self();
#endif
```

In the `MSYS64`, `uint32_t` is defined in the `<stdint.h>` header file, but anyway, I replaced these types with the custom types to avoid type definition problems on any platform.

Can you please try it with you if it works? Because I don't have a Windows platform right now..

**Comment by tallaki74** [comment]
Thank you.
But I changed the `return (uint32_t)pthread_self();` to `return (size_t)pthread_self();` because the gcc compiler warned that different size:
```
slog.c:196:12: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
  196 |     return (slog_u32_t)pthread_self();`
```
I choosed `size_t` because it is 64 bit unsigned integer on 64 bit systems and 32 bit unsigned integer on 32 bit systems.

The other thing:
Please could you replace all `__FUNCTION__` to `__func__` to meet the C99 standard:
```
slog.c:79:33: warning: ISO C does not support ‘__FUNCTION__’ predefined identifier [-Wpedantic]
   79 |             __FILE__, __LINE__, __FUNCTION__, errno);
      |                                 ^~~~~~~~~~~~
```

**Comment by tallaki74** [comment]
I would change back to `uintxx_t` the types:
from
```
typedef unsigned int            slog_u32_t;
typedef unsigned short int      slog_u16_t;
typedef unsigned char           slog_u8_t;
```
to
```
typedef uintptr_t slog_uptr_t;  /* width is 32 bits on 32 bit systems and 64 bits on 64 bit systems */
typedef uintmax_t slog_umax_t;  /* width is 32 bits on 32 bit systems and 64 bits on 64 bit systems */
typedef uint64_t  slog_u64_t;
typedef uint32_t  slog_u32_t;
typedef uint16_t  slog_u16_t;
typedef uint8_t   slog_u8_t;
```
because these are the exact width types in C99 standard.
So it could be:
```
static slog_uptr_t slog_get_tid()
{
#ifdef __linux__
    return syscall(__NR_gettid);
#else
    return (slog_uptr_t)pthread_self();
#endif
}
```
and on 64 bit system the `%u` could be `%lu`:
```
static void slog_create_tid(char *pOut, int nSize, slog_u8_t nTraceTid)
{
    if (!nTraceTid) pOut[0] = SLOG_NUL;
    else snprintf(pOut, nSize, "(%lu) ", slog_get_tid());
}
```
because:
```
slog.c:221:35: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 4 has type ‘slog_uptr_t’ {aka ‘long unsigned int’} [-Wformat=]
  221 |     else snprintf(pOut, nSize, "(%u) ", slog_get_tid());
      |                                  ~^     ~~~~~~~~~~~~~~
      |                                   |     |
      |                                   |     slog_uptr_t {aka long unsigned int}
      |                                   unsigned int
      |                                  %lu
```

**Comment by kala13x** [comment]
@tallaki74 

Changing the format specifier to `%lu` would indeed fix the warning on a 64-bit system.

However, this is not portable and could cause issues on 32-bit systems where `uintptr_t` is an unsigned int. The format specifier `%lu` expects an `unsigned long` which is typically larger than `unsigned int` on a 32-bit system. This could potentially cause incorrect output or even undefined behavior.

The C99 standard provides a set of format macros in `inttypes.h` for exactly this purpose. We should use `PRIuPTR` for `uintptr_t`. This macro will expand to the correct format specifier on both 32-bit and 64-bit systems: https://github.com/kala13x/slog/commit/de4a880b303225f8189e51774e56bc458f45ba50

```C
snprintf(pOut, nSize, "(%" PRIuPTR ") ", slog_get_tid());
```

P.S. Changed also `__FUNCTION__` to `__func__` to meet the C99 standard in a separate commit: https://github.com/kala13x/slog/commit/ecbed8cc14c952dd69b6d38539aeb22a6b82b7c8

**Comment by tallaki74** [comment]
I compiled the slog library on Debian 10 64bit with gcc, and on MSYS64 Win11 64bit with gcc.
It wasn't any errors or warnings. :-)
I attache this code, what I compiled on these systems:
[slog.tar.gz](https://github.com/kala13x/slog/files/11440729/slog.tar.gz)
Thanks.

**Comment by kala13x** [comment]
@tallaki74  Thank you.

I will close this issue not.
